### ISSUE TITLE
Switch command argument order to put variable length VCFs at the end

### ISSUE THREAD

**Issue by jeromekelleher** [sgkit-dev/bio2zarr#102]
Currently we have
```
vcf2zarr convert [OPTIONS] VCF_1... VCF_N ZARR_PATH
vcf2zarr explode [OPTIONS] VCF_1... VCF_N ICF_PATH
vcf2zarr dexplode-init [OPTIONS] VCF_1... VCF_N ICF_PATH NUM_PARTITIONS
```

This can lead to some confusing error messages when people forget an argument, so I've been wondering if we should change to put the VCFs at the end, like
```
vcf2zarr convert [OPTIONS] ZARR_PATH  VCF_1... VCF_N 
vcf2zarr explode [OPTIONS] ICF_PATH VCF_1... VCF_N
vcf2zarr dexplode-init [OPTIONS] ICF_PATH NUM_PARTITIONS VCF_1... VCF_N 
```

This is a little bit unituitive to me (I'm used to thinking about ``cp SRC DEST``), but maybe that's not so bad?

(I have a religious objection to "mandatory options" before anyone asks!)

**Comment by tomwhite** [comment]
What you have already seems better. As you said it's `cp src1 src2 ... srcn dst`.

It is possible to have a default for `NUM_PARTITIONS`? Then you could make it an option. It feels a bit odd to mix it with paths.

**Comment by jeromekelleher** [comment]
I tend to agree, but the click errors are really quite unhelpful at the moment:
```
$ vcf2zarr dexplode-init a.vcf
Usage: vcf2zarr dexplode-init [OPTIONS] VCFS... ICF_PATH NUM_PARTITIONS
Try 'vcf2zarr dexplode-init --help' for help.

Error: Missing argument 'VCFS...'.
```

```
$ vcf2zarr dexplode-init a.vcf b.icf
Usage: vcf2zarr dexplode-init [OPTIONS] VCFS... ICF_PATH NUM_PARTITIONS
Try 'vcf2zarr dexplode-init --help' for help.

Error: Missing argument 'VCFS...'.
```
$ vcf2zarr dexplode-init a.vcf b.icf 10
```
works

So, it seems like click only starts looking at the variadic arguments after the others have been "allocated", even when the variadic arguments come first.

If we switch the ordering around, we get 
```
$ python3 -m bio2zarr vcf2zarr dexplode-init
Usage: python -m bio2zarr vcf2zarr dexplode-init [OPTIONS] ICF_PATH
                                                 NUM_PARTITIONS VCFS...
Try 'python -m bio2zarr vcf2zarr dexplode-init --help' for help.

Error: Missing argument 'ICF_PATH'.
jk@holly$ python3 -m bio2zarr vcf2zarr dexplode-init a.icf
Usage: python -m bio2zarr vcf2zarr dexplode-init [OPTIONS] ICF_PATH
                                                 NUM_PARTITIONS VCFS...
Try 'python -m bio2zarr vcf2zarr dexplode-init --help' for help.

Error: Missing argument 'NUM_PARTITIONS'.
jk@holly$ python3 -m bio2zarr vcf2zarr dexplode-init a.icf b.vcf
Usage: python -m bio2zarr vcf2zarr dexplode-init [OPTIONS] ICF_PATH
                                                 NUM_PARTITIONS VCFS...
Try 'python -m bio2zarr vcf2zarr dexplode-init --help' for help.

Error: Invalid value for 'NUM_PARTITIONS': 'b.vcf' is not a valid integer.
jk@holly$ python3 -m bio2zarr vcf2zarr dexplode-init a.icf 10 b.vcf
Usage: python -m bio2zarr vcf2zarr dexplode-init [OPTIONS] ICF_PATH
                                                 NUM_PARTITIONS VCFS...
Try 'python -m bio2zarr vcf2zarr dexplode-init --help' for help.

Error: Invalid value for 'VCFS...': File 'b.vcf' does not exist.
```
which is much less confusing for users.

I don't really feel like fighting with click over this, so am tempted to just go with putting the variadic arguments at the end.

Re the ``NUM_PARTITIONS`` argument, I don't really see the point in providing a default - this is an advanced operation, and we want the user to think about how many partitions they want to split the work over in their cluster.

**Comment by tomwhite** [comment]
It seems wrong to adjust the args order to satisfy a limitation in Click.

If `dexplode-init` is an advanced operation then users will probably tolerate a mandatory option :)

**Comment by jeromekelleher** [comment]
> It seems wrong to adjust the args order to satisfy a limitation in Click.

Yeah, I agree. But, I'd rather be pragmatic with a limited time budget than be a purist here. There's really no right answer with CLI stuff, so whatever leads to less overall confusion may be best.

> dexplode-init is an advanced operation then users will probably tolerate a mandatory option :)

Haha, it's not the *users* who have to tolerate it, I'm sure they'd be fine :smile:

**Comment by jeromekelleher** [comment]
Adding this to 0.1.0 release, as we'll either need to change or accept that this is the way it is then (and documented). I'm going to try documenting this soon, and we'll see how easy it is to explain.

**Comment by jeromekelleher** [comment]
OK, going to close this as "wontfix". It's too confusing to swap the order and the error messages aren't *that* confusing.
