### ISSUE TITLE
Docs deploy failing

### ISSUE THREAD

**Issue by jeromekelleher** [sgkit-dev/bio2zarr#140]
https://github.com/sgkit-dev/bio2zarr/actions/runs/8816016143
```
Annotations
2 errors and 1 warning
deploy
Tag "0.0.6" is not allowed to deploy to github-pages due to environment protection rules.
deploy
```
Can you have a look please @benjeffery?

**Comment by benjeffery** [comment]
The action won't work on a tag - but was successfully deployed in https://github.com/sgkit-dev/bio2zarr/actions/runs/8816001846 when the commit was pushed to main.

Down the line when we have versioned docs the tag push will update the `stable` docs.
