### ISSUE TITLE
Memory bound in dencode substantially underestimated

### ISSUE THREAD

**Issue by jeromekelleher** [sgkit-dev/bio2zarr#141]
Looks like it was off by quite a bit on GeL. Can you update please @benjeffery?

**Comment by jeromekelleher** [comment]
The only thing I can think of is string columns being handled incorrectly, but that's not what you saw I think?

**Comment by benjeffery** [comment]
All partitions were killed while processing `call_FT` which is indeed a string field.

**Comment by jeromekelleher** [comment]
That'll be it then. Good, we can figure that one out, hopefully.
