### ISSUE TITLE
`dencode-partition` fails with `AssertionError`

### ISSUE THREAD

**Issue by benjeffery** [sgkit-dev/bio2zarr#144]
![Screenshot from 2024-04-25 12-14-47](https://github.com/sgkit-dev/bio2zarr/assets/8552/d48edb04-9045-4e69-9ea2-b1ab842c622f)

**Comment by benjeffery** [comment]
This looks like empty partitions, similar to the issue we had on explode?

**Comment by benjeffery** [comment]
I can confirm that in `IntermediateColumnarFormatField.chunks`
`chunk_num_records[start_chunk:]` is `[]` and `chunk_cumulative_records[start_chunk + 1 :]` is also `[]`

**Comment by jeromekelleher** [comment]
Can you run that again with ``-vv`` please to get debug output?

Can you have a look at the ICF metadata file and see if there any partition with ``"num_records": 0"``?

**Comment by benjeffery** [comment]
![Screenshot from 2024-04-25 16-01-01](https://github.com/sgkit-dev/bio2zarr/assets/8552/a3413a11-7281-42ec-8b53-e33c908f6a4d)

There are no zeros in the ICF metadata.

**Comment by jeromekelleher** [comment]
What version of bio2zarr have you here? Line 605 is nowhere near ``iter_values`` in main

**Comment by jeromekelleher** [comment]
Can you view the icf metadata please, and show the last few partitions. Must be something odd to do with tabix indexing

**Comment by benjeffery** [comment]
> What version of bio2zarr have you here? Line 605 is nowhere near `iter_values` in main

This was on `e6b9a` after #136 was merged.

**Comment by jeromekelleher** [comment]
> This was on e6b9a after #136 was merged.

I don't think it can be - this is line 605 on that commit: https://github.com/sgkit-dev/bio2zarr/blob/e6b9a1970984c073fa2249fc45b41c2bb5d8fa3b/bio2zarr/vcf.py#L605

**Comment by jeromekelleher** [comment]
Also it looks like you're pulling the bio2zarr code from a local directory - it would be better to install to the environment. There's regular releases for just this.

**Comment by benjeffery** [comment]
> > This was on e6b9a after #136 was merged.
> 
> I don't think it can be - this is line 605 on that commit:
> 
> https://github.com/sgkit-dev/bio2zarr/blob/e6b9a1970984c073fa2249fc45b41c2bb5d8fa3b/bio2zarr/vcf.py#L605

It's 685, not 605. Sorry I can't cut and paste things!

**Comment by benjeffery** [comment]
> 'import pickle; print(pickle.load(open("[ICF_PATH]/REF/p14761/chunk_index", "rb")))'

![Screenshot from 2024-04-26 11-47-08](https://github.com/sgkit-dev/bio2zarr/assets/8552/6c677245-dbfa-454e-9ca5-86fa40916dc3)

**Comment by jeromekelleher** [comment]
> It's 685, not 605. Sorry I can't cut and paste things!

Ahhhh - sorry, I should have zoomed in! :facepalm:

**Comment by jeromekelleher** [comment]
OK, looks like it's a problem with the indexing code. We should have ``start_chunk=0`` (there's only one chunk) but for some reason it's coming out as 1. Would you mind dropping into the debugger please and seeing if you can track this down @benjeffery?

**Comment by jeromekelleher** [comment]
I'm going to see if I can replicate on the chr2 1000G data - we'll see how long it all takes when there's only 40 processes.

**Comment by jeromekelleher** [comment]
I can't reproduce this on 1000G - seems to work fine with maximal partitioning. There's quite a lot fewer variants though.

Is it just this particular partition that the error occurs on or are there others?

**Comment by benjeffery** [comment]
There were a few hundred that failed with this error - digging into this today.

**Comment by benjeffery** [comment]
Trying to understand what is going on here:
In `iter_values` We end up with a `chunk_offset` of 29838. This is greater than the largest value in `chunk_record_index` so we end up with a `start_chunk` that is greater than anything in the chunk record index, so `chunks` then returns an empty list.

**Comment by benjeffery** [comment]
I've also checked and it is 550 failing partitions spread non-contiguosly from 1708-5985.

**Comment by benjeffery** [comment]
Ah-ha, wonder if this has something to do with it. Running `dexplode-init` again and `check_overlap` finds an overlap. That check was added after I exploded these VCFs.

**Comment by jeromekelleher** [comment]
Ahhhh

**Comment by jeromekelleher** [comment]
We shouldn't have overlaps here though, right? Can you give some details?

**Comment by benjeffery** [comment]
The list of filename, partition.region.start and partition.reigion.end looks like this:
![Screenshot from 2024-04-30 14-59-05](https://github.com/sgkit-dev/bio2zarr/assets/8552/4c6834fe-1693-4146-bb5c-fc3f45883957)


Really odd that a VCF in the middle contains `1`. Checking the VCF to be sure.

**Comment by jeromekelleher** [comment]
A bunch of weird stuff here... are you sure the files are all part of the same set?

**Comment by benjeffery** [comment]
They are all in the same folder and have the same naming convention. The 58219159 file contains variants that start at that position.

**Comment by benjeffery** [comment]
So... that one VCF file, the `CSIIndex` has the first indexed position as `1`. No other VCFs in the set have this.

**Comment by benjeffery** [comment]
So this is the only index file that has a bin (bin `9`) which is the first bin on it's level. Tracing this all the way back to the bytes in the CSI file confirms this.
I'm re-indexing the file to see if this is the expected behavior.

**Comment by benjeffery** [comment]
58720256

**Comment by jeromekelleher** [comment]
OK, I'm rejigging a bunch of things to avoid using the record counts from the indexes. They're really not reliable, and not present in a lot of cases.
