### ISSUE TITLE
Setup `release`/CD workflow 

### ISSUE THREAD

**Issue by ravwojdyla** [sgkit-dev/bio2zarr#154]
#152 adds CI workflow, it would be great to have a CD workflow as well. I am happy to handle that, but will wait for some open PRs to merge, to avoid conflicts.

**Comment by jeromekelleher** [comment]
That would be great, thanks @ravwojdyla! Feel free to merge the open PRs after rebasing?

**Comment by jeromekelleher** [comment]
Would be nice to get this into place fairly soon @ravwojdyla - hoping to get onto the first proper release very soon now, and would like to try the automated version while we're still on the 0.0.x series
