### ISSUE TITLE
Fix project email

### ISSUE THREAD

**Issue by jeromekelleher** [sgkit-dev/bio2zarr#155]
Currently "sgkit Developers", email = "project@pystatgen.org"},

**Comment by ravwojdyla** [comment]
@jeromekelleher what's the correct email?

**Comment by jeromekelleher** [comment]
It's ``project@sgkit.dev`` [for sgkit](https://github.com/sgkit-dev/sgkit/blob/b0a94ebda70ce50b6951e4f1a2ee3890fc01df2a/setup.cfg#L4C16-L4C33), so may as well use that.
