### ISSUE TITLE
Test coverage in CI

### ISSUE THREAD

**Issue by jeromekelleher** [sgkit-dev/bio2zarr#156]
One thing I'm really missing is useable tracking of test coverage. I've been pretty unimpressed by codecov recently, are there any decent alternatives? Have you looked at this sort of thing recently @ravwojdyla ?

**Comment by benjeffery** [comment]
We've been using coveralls over at phylokit: https://github.com/jeromekelleher/phylokit/pull/41#issuecomment-2068923144 seems to be working well?

**Comment by jeromekelleher** [comment]
Yes, we've not looked at it for a long time and it still works! Shall we give it a go here?

**Comment by benjeffery** [comment]
Yep, I'm happy to add that in.

**Comment by jeromekelleher** [comment]
Let's not bother till sgkit 0.8.0 is out, see #158
