### ISSUE TITLE
`dexplode_init` fails if `num_partitions`  is < 2*`num_vcfs`.

### ISSUE THREAD

**Issue by benjeffery** [sgkit-dev/bio2zarr#159]
Line 301 in `check_overlap`:
`TypeError '>' not supported between instances of 'NoneType' and 'int'`

**Comment by jeromekelleher** [comment]
This is a dupe of #146 I think. There's a workaround queued up in #145

**Comment by jeromekelleher** [comment]
I don't see how the number of partitions would induce this though?

**Comment by jeromekelleher** [comment]
I'm going to close this as completed in #164, but do reopen if it rears its ugly head again @benjeffery
