### ISSUE TITLE
Add --one-based option to dexplode-partition and dencode-partition

### ISSUE THREAD

**Issue by jeromekelleher** [sgkit-dev/bio2zarr#168]
Useful for things that want to count from 1 to N inclusive. 

Not sure what the nicest short form is, could do
```
vcf2zarr dexplode-partition -1 [ICF] [partition id]
```
but maybe that's confusing?

See #147

**Comment by benjeffery** [comment]
I think only having a long-form option of something like `--1-based` would be clearest.

**Comment by jeromekelleher** [comment]
Yeah, it's a fair starting point, can always add a short-form later if needed. I think best to fully spell though, like ``--one-based``
