### ISSUE TITLE
Could `dencode_init` return an upper memory use bound?

### ISSUE THREAD

**Issue by benjeffery** [sgkit-dev/bio2zarr#188]
Currently when running `dencode_partition` I'm having to guess the RAM needed and increase it as the test partition fails. Might be nice for the user to have some way of knowing how much will be needed?

**Comment by jeromekelleher** [comment]
dencode_init returns this as part of the output. It's an underestimate currently (#186), but a reasonable starting point.

**Comment by jeromekelleher** [comment]
The output formatting has been improved recently, I'll document usage soon.

**Comment by benjeffery** [comment]
Ah great, i'm still on 0.0.9, so hadn't seen that.
