### ISSUE TITLE
CD publish to pypi didn't trigger on release

### ISSUE THREAD

**Issue by jeromekelleher** [sgkit-dev/bio2zarr#207]
I just created a 0.0.10 release using the GitHub UI and the CD action pushed a release to test pypi, but not the real pypi. 

See here: https://github.com/sgkit-dev/bio2zarr/actions/runs/9092219868

Do you know what happened here @ravwojdyla?

**Comment by jeromekelleher** [comment]
Oh, hold on, the release *is* on pypi: https://pypi.org/project/bio2zarr/0.0.10/#history

I only noticed this as I was manually uploading the files, so maybe something odd happened there? I'm confused!

**Comment by ravwojdyla** [comment]
@jeromekelleher I think the pypi release workflow is here: https://github.com/sgkit-dev/bio2zarr/actions/runs/9092219867, looks like the files were uploaded.

**Comment by ravwojdyla** [comment]
@jeromekelleher the CD workflow as it is implemented right now (which afair mirrors the sgkit setup) will be triggered for a tag and a published release separately.

Tag goes to test-pypi: https://github.com/sgkit-dev/bio2zarr/blob/4461ba173f9faa135462ed0583a0fb38ef6e71cc/.github/workflows/cd.yml#L66-L67

Published release goes to pypi: https://github.com/sgkit-dev/bio2zarr/blob/4461ba173f9faa135462ed0583a0fb38ef6e71cc/.github/workflows/cd.yml#L46-L47

**Comment by jeromekelleher** [comment]
Ahh, they were on separate workflow runs, now I get it. OK great, it's all working then, thanks!
