### ISSUE TITLE
Returning a string from `.mkschema`

### ISSUE THREAD

**Issue by hyanwong** [sgkit-dev/bio2zarr#220]
It might be handy if the (undocumented) `vcf2zarr.mkschema` command returned the schema as a string if the second ("out") argument isn't given. You could then have a `schema` argument to pass this in to `vcf2zarr.encode` (it would then be an error to specify both `schema` and `schema_path`).

This would allow neater alteration of the schema programatically.

**Comment by jeromekelleher** [comment]
We'll probably want to have richer tools for working with schemas generally.

Like I say, the Python API just exists to support the CLI currently, I would actively discourage anyone from using it for anything.

Given this, I'm going to close this as "wontfix" (and open an issue to document the Python API status prominently)
