### ISSUE TITLE
Move region index creation from vcztools

### ISSUE THREAD

**Issue by tomwhite** [sgkit-dev/bio2zarr#290]
We should remove the `vcztools index` command and have bio2zarr create [region indexes](https://github.com/sgkit-dev/vcztools/pull/37) instead. (Region indexes are used by vcztools to do efficient region queries.) Then bio2zarr would be concerned only with *writing* vcz and vcztools only with *reading* vcz.

This was suggested before (https://github.com/sgkit-dev/vcztools/pull/37#issuecomment-2252360946), but it would be good to move it out of vcztools now before releasing it.

Should index creation be a part of `vcf2zarr encode`?

**Comment by jeromekelleher** [comment]
> Should index creation be a part of vcf2zarr encode

I think that's the simplest approach all right. It's a very simple operation and we can think about how to make it more generally accessible later on.
