### ISSUE TITLE
Creating directories in explode_init takes 15min

### ISSUE THREAD

**Issue by benjeffery** [sgkit-dev/bio2zarr#82]
Might be nice to parallelise this and add progress

**Comment by jeromekelleher** [comment]
On very large dataset

**Comment by benjeffery** [comment]
Yes sorry, should have been specific - this is when I have ~4000 partitions, resulting in about 150,000 directories.

**Comment by jeromekelleher** [comment]
Did you have 4000 workers on this??? (See #89)

**Comment by jeromekelleher** [comment]
This should be much improved in latest version btw - only the top level dirs are created by init, the partition dirs are made as part of ``explode-partition``
